development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:efce19771ed570a82d9189fd6e13b196@spinyfin.redistogo.com:10024/
  channel_prefix: sloth_production


#TODO: change the production URL if you push your app to, say, Heroku later on.
